# Generated by Django 3.2.19 on 2023-06-21 14:44

from django.db import migrations, models
import lmsApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='datecount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(default=lmsApp.models.get_expiry),
        ),
    ]
